spring:
  application:
    name: Microservice-Ecommerce-Application

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/ecommerce_application?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    postgres:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/ecommerce_application
      username: postgres
      password: root
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

  jpa:
    open-in-view: false
    mysql:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
    postgres:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true

#server:
#  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: Microservice Ecommerce Application
    description: Microservice Ecommerce Application built by me
    version: 1.0.0
