FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/Microservice-Ecommerce-Application-0.0.1-SNAPSHOT.jar Microservice-Ecommerce-Application-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD ["java","-jar","Microservice-Ecommerce-Application-0.0.1-SNAPSHOT.jar"]